apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: pod
  name: pod
spec:
  containers:
  - image: hashicorp/http-echo
    name: pod
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: pod
  name: pod
spec:
  containers:
  - image: hashicorp/http-echo
    name: pod
    args: ["-text","version1"]
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
